### ISSUE TITLE
remapping keys

### ISSUE THREAD

**Issue by chad-betamax** [Fanteria/todotxt-tui#39]
How would one remap the navigation keys to the arrow-keys  ?

so up-arrow/down-arrow to move in the list 
and
right-arrow/left-arrow to change pane focus

**Comment by Fanteria** [comment]
Try:

```toml
[list_keybind]
Down = "ListDown"
Up = "ListUp"
```
