### ISSUE TITLE
Update UI when TODO-file is updated from elsewhere

### ISSUE THREAD

**Issue by tkbremnes** [Fanteria/todotxt-tui#41]
One of the (IMO) best features of todo.txt is that it can be updated from a variety of tools. It'd be great if todotxt-tui would update the UI when a TODO-file is updated from elsewhere.

Right now todotxt-tui will overwrite the file as it is shown, which can lead to data-loss.

**Comment by tkbremnes** [comment]
I tried adding an item at the bottom of the list using Helix while todotxt-tui was open. Change did not appear in the TUI.

Pressing `u` does make changes appear, hoever_ I can't navigate down to the item.

**Comment by Fanteria** [comment]
I can reproduce the bug where it is not possible to navigate to the new item. However, for the update issue, I am not sure. Please provide the log.  

To enable logging, add a `log4rs.yaml` file to the `.config/todotxt-tui/` directory. The file should contain the following configuration:

```yaml
refresh_rate: 30 seconds
appenders:
  file:
    kind: file
    path: "log.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {M} [{l}] {m}{n}"

root:
  level: trace
  appenders:
    - file
```

Once you've added the file, start `todotxt-tui` and update the `todo.txt` file. For example:

```bash
echo HI >> /path/to/your/todo.txt 
```

The log file should be created in the directory where you run `todotxt-tui`.
